# Generated by Django 3.2.8 on 2021-11-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
