# Generated by Django 3.2.8 on 2021-12-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_surveytoken_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyToken',
        ),
    ]
