# Generated by Django 3.2.8 on 2021-12-01 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_surveytoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
