# Generated by Django 3.2.8 on 2021-12-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211016_1343'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='settouser',
            constraint=models.CheckConstraint(check=models.Q(('can_admin', True), ('can_write', True), ('can_read', True), _connector='OR'), name='at_least_one_permission'),
        ),
    ]
