# Generated by Django 3.2.8 on 2021-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_datapair_dashboard_d_dataset_cd462b_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['name'], name='dashboard_d_name_6d8a70_idx'),
        ),
        migrations.AddIndex(
            model_name='settouser',
            index=models.Index(fields=['dataset', 'user'], name='dashboard_s_dataset_5923ef_idx'),
        ),
    ]
