# Generated by Django 3.2.8 on 2021-12-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_settouser_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settouser',
            name='permission',
            field=models.CharField(choices=[('R', 'read'), ('W', 'write'), ('A', 'admin')], default='R', max_length=5),
        ),
    ]
