# Generated by Django 3.2.8 on 2021-12-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settouser',
            name='can_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settouser',
            name='can_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settouser',
            name='can_write',
            field=models.BooleanField(default=False),
        ),
    ]
