# Generated by Django 3.2.8 on 2021-10-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20211016_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapair',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairToDataset', to='dashboard.dataset'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='users',
            field=models.ManyToManyField(related_name='dataToUsers', through='dashboard.SetToUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settouser',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setToDataset', to='dashboard.dataset'),
        ),
        migrations.AlterField(
            model_name='settouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setToUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
