# Generated by Django 3.2.9 on 2021-12-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dataset_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='size',
            new_name='dataset_size',
        ),
        migrations.RenameField(
            model_name='settouser',
            old_name='size',
            new_name='dataset_size',
        ),
    ]
