# Generated by Django 3.2.9 on 2021-12-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211204_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_size',
        ),
        migrations.RemoveField(
            model_name='settouser',
            name='dataset_size',
        ),
    ]
