# Generated by Django 3.2.8 on 2021-12-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_surveytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytoken',
            name='key',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
